spring.application.name=progettoPrenotazioni
spring.datasource.url=jdbc:postgresql://localhost:5432/progettoPrenotazioni
spring.datasource.username=postgres
spring.datasource.password=1234
spring.datasource.drive-class-name=org.postgresql.Driver
spring.jpa.hibernate.ddl-auto=update

